version: '3.1'

services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    networks:
      - ldap-network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "8443:443"
    depends_on:
      - ldap
    networks:
      - ldap-network

  ##################################SERVER###################################################
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ldap-network
    

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: unless-stopped
  #   tty: true
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - ldap-network

  php:
    build: ./server/php
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
    # depends_on:
    #   - mariadb
    ports:
      - "9999:9000"
    networks:
      - ldap-network

  # mariadb:
  #   image: mariadb:10.5
  #   restart: unless-stopped
  #   tty: true
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root
  #     MARIADB_DATABASE: db_hr
  #     MARIADB_USER: hr
  #     MARIADB_PASSWORD: 1234
  #   volumes:
  #     - ./database:/var/lib/mysql
  #     - ./server/mariadb/my.cnf:/etc/mysql/my.cnf
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - ldap-network

networks:
  ldap-network:
    driver: bridge
